name: main
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: run linter
        run: yarn lint

      - name: run test
        run: yarn install --immutable
        run: yarn run test
